### PR TITLE
Make past meetings paler to ease calendar usage

### PR DESCRIPTION
**Pull request by marcochiesi**
Refs https://meta.trac.wordpress.org/ticket/6868

### CODE REVIEW

**Comment by ryelle** [comment]
This is used on https://make.wordpress.org/meetings/

Screenshot 2024-09-17 at 3 25 56 PM

It's also used on https://learn.wordpress.org/online-workshops/

Screenshot 2024-09-17 at 3 25 20 PM

And while we discussed that the lower contrast was okay for Make (since the style may be updated soon), the calendar on Learn needs to stay at 4.5+ contrast. Eventually, I think the Make calendar will look more like the the Learn calendar, and they can both use the same past-event style (just maybe not opacity).

@adamwoodnz Is this page on your radar for the Make refresh?

**Comment by adamwoodnz** [comment]
> Eventually, I think the Make calendar will look more like the the Learn calendar, and they can both use the same past-event style (just maybe not opacity).

> @adamwoodnz Is this page on your radar for the Make refresh?

Yes, my current thinking is to move the new styles from Learn to this plugin so that both share the same style. I've just created an [issue](https://github.com/WordPress/meeting-calendar/issues/158).

**Comment by adamwoodnz** [comment]
Now that the redesigned calendar was shipped I'm going to start a discussion on the meta ticket about how these past events should be styled, so that we can maintain contrast ratios.

**Comment by adamwoodnz** [comment]
Thanks for your efforts on this, the past event styling has now been merged in https://github.com/WordPress/meeting-calendar/pull/161

**Pull request closed without merging**
